Issue 17
trpo2021/cw-is-042_unit-converter pull request #24
Opened 2021-06-04 10:18 UTC by NikitaKolodey

Добавил тест 5 в файл с тестами.

2021-06-04 10:19 UTC, NikitaKolodey commented
Нашел некорректное поведение функции is_alpha.

2021-06-04 10:24 UTC, Young-Sailor requested changes
В функции is_alpha добавь следующие строки кода:
```int tmp = strlen(string);
if (tmp == 0) {
    return false;
}```

2021-06-04 10:30 UTC, Young-Sailor approved these changes
Хорошо, проблема решена. Продолжай писать тесты.

2021-06-04 12:58 UTC, Young-Sailor requested changes
Отформатируй.

2021-06-05 11:15 UTC, Young-Sailor approved these changes
Тесты выполнены хорошо. Теперь протестируй оставшиеся функции в check.c

2021-06-05 12:59 UTC, Young-Sailor approved these changes
Приступай к тестированию функции 'is_appropriate'.

2021-06-06 10:10 UTC, Young-Sailor approved these changes

2021-06-06 10:38 UTC, Young-Sailor approved these changes

2021-06-06 16:43 UTC, Young-Sailor approved these changes
Тесты выполнены хорошо. Работу на данной ветке можно завершать.

2021-06-06 16:45 UTC, merged